language: "pt_br"

pipeline:
  - name: "benchmark_sources.components.HFTransformerNLP.HFTransformersNLP"
    model_name: "bert_portuguese"
  - name: "benchmark_sources.components.lm_tokenizer.LanguageModelTokenizerCustom"
    "intent_tokenization_flag": False
    "intent_split_symbol": "_"
  - name: "benchmark_sources.components.lm_featurizer.LanguageModelFeaturizerCustom"
  - name: CountVectorsFeaturizer
    analyzer: char
    min_ngram: 3
    max_ngram: 3
  - name: DIETClassifier
    entity_recognition: False
    BILOU_flag: False
    batch_size: [64, 128]