language: "pt"

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char"
    min_ngram: 3
    max_ngram: 3
    token_pattern: "(?u)\\b\\w+\\b"
  - name: "bothub_benchmarker.benchmark_sources.components.diet_classifier.DIETClassifierCustom"
    epochs: 150
    entity_recognition: True
    BILOU_flag: False
  - name: SpacyEntityExtractor
