language: "pt_br"


pipeline:
  - name: "bothub_benchmarker.benchmark_sources.components.preprocessing.Preprocessing"
    language: "pt_br"
  - name: "bothub_benchmarker.benchmark_sources.components.hf_transformer.HFTransformersNLPCustom"
    model_name: "bert_portuguese"
  - name: "bothub_benchmarker.benchmark_sources.components.lm_tokenizer.LanguageModelTokenizerCustom"
    "intent_tokenization_flag": False
    "intent_split_symbol": "_"
  - name: "bothub_benchmarker.benchmark_sources.components.lm_featurizer.LanguageModelFeaturizerCustom"
  - name: CountVectorsFeaturizer
    analyzer: 'char_wb'
    min_ngram: 3
    max_ngram: 3
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: "bothub_benchmarker.benchmark_sources.components.diet_classifier.DIETClassifierCustom"
    random_seed: 7
    epochs: 200
    entity_recognition: True
    BILOU_flag: False
    number_of_transformer_layers: 4
    transformer_size: 256
    drop_rate: 0.2
    weight_sparcity: 0.95
    batch_size: [64, 256]
    embedding_dimension: 20
    hidden_layer_sizes:
      text: [256, 64]