language: "pt_br"

pipeline:
  - name: "bothub_benchmarker.benchmark_sources.components.preprocessing.Preprocessing"
    language: "pt_br"
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
    analyzer: char
    min_ngram: 3
    max_ngram: 3
    token_pattern: "(?u)\\b\\w+\\b"
  - name: "bothub_benchmarker.benchmark_sources.components.diet_classifier.DIETClassifierCustom"
    epochs: 300
    entity_recognition: True
    BILOU_flag: False
