language: "pt_br"

pipeline:
  - name: "optimized_spacy_nlp_with_labels"
  - name: "tokenizer_spacy_with_labels"
  - name: "intent_featurizer_spacy"
  - name: "intent_classifier_tensorflow_embedding"
    similarity_type: "inner"
  - name: "ner_crf"
  - name: "ner_spacy"
  - name: "crf_label_as_entity_extractor"